### ISSUE TITLE
[Suggestion] Full Moon Blood Moons

### ISSUE THREAD

**Issue by InsomniaKitten** [lumien231/Bloodmoon#9]
It would be sweet to have a config option to force blood moons to occur on a full moon instead of relying on random chance.

**Comment by chorvus** [comment]
I would like this feature for a pack project I'm working on.

It shouldn't be too hard to configurable day intervals for a guaranteed BM along with the random chance to get one, just to keep things interesting every now and then.

I could try to work on it myself and submit a PR, might take a while since I'm still taking my first steps with modding.

Love all your mods by the way!
